In [1]:
import pandas as pd
from sqlalchemy import create_engine

# Connect to your MySQL database
engine = create_engine('mysql+pymysql://root:22kq1a54c7@localhost:3306/ecommerce_db')

# Read the clean table directly into a DataFrame named 'f'
f = pd.read_sql("SELECT * FROM customer_transactions", con=engine)

# Confirm everything is there (It will show all columns including TotalSales!)
print(f.shape)
f.head()

(526052, 9)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalSales
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34

In [3]:
rfm_data = f[f["CustomerID"] != -1].copy()

print(rfm_data.shape)

(392732, 9)

In [5]:
import pandas as pd

rfm_data["InvoiceDate"] = pd.to_datetime(rfm_data["InvoiceDate"])

In [7]:
reference_date = rfm_data["InvoiceDate"].max() + pd.Timedelta(days=1)

print(reference_date)

2011-12-10 12:50:00

In [9]:
rfm = rfm_data.groupby("CustomerID").agg({
    "InvoiceDate": lambda x: (reference_date - x.max()).days,
    "InvoiceNo": "nunique",
    "TotalSales": "sum"
})

In [11]:
rfm.columns = ["Recency", "Frequency", "Monetary"]

In [13]:
print(rfm.shape)

rfm.head()

(4339, 3)

            Recency  Frequency  Monetary
CustomerID
12346.0         326          1  77183.60
12347.0           2          7   4310.00
12348.0          75          4   1797.24
12349.0          19          1   1757.55
12350.0         310          1    334.40

In [26]:
rfm.describe()

           Recency    Frequency       Monetary
count  4339.000000  4339.000000    4339.000000
mean     92.518322     4.271952    2048.215923
std     100.009747     7.705493    8984.248352
min       1.000000     1.000000       0.000000
25%      18.000000     1.000000     306.455000
50%      51.000000     2.000000     668.560000
75%     142.000000     5.000000    1660.315000
max     374.000000   210.000000  280206.020000

In [28]:
# Recency Score
rfm["R_Score"] = pd.qcut(
    rfm["Recency"],
    q=5,
    labels=[5,4,3,2,1]
)

# Frequency Score
rfm["F_Score"] = pd.qcut(
    rfm["Frequency"].rank(method="first"),
    q=5,
    labels=[1,2,3,4,5]
)

# Monetary Score
rfm["M_Score"] = pd.qcut(
    rfm["Monetary"].rank(method="first"),
    q=5,
    labels=[1,2,3,4,5]
)

In [30]:
# Overall Score
rfm["Overall_Score"] = (
    rfm["R_Score"].astype(int)
    + rfm["F_Score"].astype(int)
    + rfm["M_Score"].astype(int)
)

# Segment based on Overall Score
rfm["Segment"] = pd.cut(
    rfm["Overall_Score"],
    bins=[2, 5, 8, 11, 13, 15],
    labels=[
        "Lost Customers",
        "At Risk",
        "Potential Loyalists",
        "Loyal Customers",
        "Champions"
    ]
)

In [ ]:
rfm["Segment"] = rfm["RFM_Score"].replace(
    segment_map,
    regex=True
)

In [31]:
valid = [
    "Champions",
    "Loyal Customers",
    "Potential Loyalists",
    "At Risk",
    "Lost Customers"
]

rfm.loc[~rfm["Segment"].isin(valid), "Segment"] = "Potential Loyalists"

In [33]:
rfm["Segment"].value_counts()

Segment
Potential Loyalists    1534
Lost Customers          749
Loyal Customers         745
Champions               732
At Risk                 579
Name: count, dtype: int64

In [35]:
segment_revenue = (
    rfm.groupby("Segment")["Monetary"]
    .sum()
    .sort_values(ascending=False)
)

print(segment_revenue)

Segment
Champions              5363877.08
Loyal Customers        1657198.29
At Risk                 848772.96
Potential Loyalists     732921.92
Lost Customers          284438.64
Name: Monetary, dtype: float64

In [37]:
(
segment_revenue /
rfm["Monetary"].sum()
*100
).round(2)

Segment
Champions              60.36
Loyal Customers        18.65
At Risk                 9.55
Potential Loyalists     8.25
Lost Customers          3.20
Name: Monetary, dtype: float64

In [39]:
rfm = rfm.sort_values(
    by="Monetary",
    ascending=False
)

rfm["Decile"] = pd.qcut(
    rfm["Monetary"].rank(
        ascending=False,
        method="first"
    ),
    q=10,
    labels=[f"Decile {i}" for i in range(1,11)]
)

In [41]:
decile_revenue = (
    rfm.groupby("Decile")["Monetary"]
    .sum()
)

C:\Users\gouth\AppData\Local\Temp\ipykernel_30768\484175512.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  rfm.groupby("Decile")["Monetary"]

In [43]:
(
decile_revenue /
rfm["Monetary"].sum()
*100
).round(2)

Decile
Decile 1     61.45
Decile 2     13.23
Decile 3      8.16
Decile 4      5.51
Decile 5      3.85
Decile 6      2.82
Decile 7      2.01
Decile 8      1.48
Decile 9      0.97
Decile 10     0.51
Name: Monetary, dtype: float64

In [121]:
rfm.head(20)

,Recency,Frequency,Monetary,R_Score,M_Score,F_Score,RFM_Score,Segment,Decile
CustomerID,,,,,,,,,
14646.0,2,74,280206.02,5,5,5,555,Champions,Decile 1
18102.0,1,60,259657.30,5,5,5,555,Champions,Decile 1
17450.0,8,46,194390.79,5,5,5,555,Champions,Decile 1
16446.0,1,2,168472.50,5,5,2,525,Potential Loyalists,Decile 1
14911.0,1,201,143711.17,5,5,5,555,Champions,Decile 1
12415.0,24,21,124914.53,4,5,5,455,Champions,Decile 1
14156.0,10,55,117210.08,5,5,5,555,Champions,Decile 1
17511.0,3,31,91062.38,5,5,5,555,Champions,Decile 1
16029.0,39,63,80850.84,3,5,5,355,Loyal Customers,Decile 1
12346.0,326,1,77183.60,1,5,1,115,Lost Customers,Decile 1
16684.0,4,28,66653.56,5,5,5,555,Champions,Decile 1
14096.0,4,17,65164.79,5,5,5,555,Champions,Decile 1
13694.0,4,50,65039.62,5,5,5,555,Champions,Decile 1
15311.0,1,91,60632.75,5,5,5,555,Champions,Decile 1
13089.0,3,97,58762.08,5,5,5,555,Champions,Decile 1
17949.0,1,45,58510.48,5,5,5,555,Champions,Decile 1
15769.0,7,26,56252.72,5,5,5,555,Champions,Decile 1
15061.0,4,48,54534.14,5,5,5,555,Champions,Decile 1
14298.0,8,44,51527.30,5,5,5,555,Champions,Decile 1
14088.0,10,13,50491.81,5,5,5,555,Champions,Decile 1

In [45]:
rfm.head()

,Recency,Frequency,Monetary,R_Score,F_Score,M_Score,RFM_Score,Segment,Decile
CustomerID,,,,,,,,,
14646.0,2,74,280206.02,5,5,5,555,Champions,Decile 1
18102.0,1,60,259657.30,5,5,5,555,Champions,Decile 1
17450.0,8,46,194390.79,5,5,5,555,Champions,Decile 1
16446.0,1,2,168472.50,5,3,5,535,Loyal Customers,Decile 1
14911.0,1,201,143711.17,5,5,5,555,Champions,Decile 1

In [47]:
rfm = rfm.reset_index()

In [49]:
rfm.head()

,CustomerID,Recency,Frequency,Monetary,R_Score,F_Score,M_Score,RFM_Score,Segment,Decile
0,14646.0,2,74,280206.02,5,5,5,555,Champions,Decile 1
1,18102.0,1,60,259657.30,5,5,5,555,Champions,Decile 1
2,17450.0,8,46,194390.79,5,5,5,555,Champions,Decile 1
3,16446.0,1,2,168472.50,5,3,5,535,Loyal Customers,Decile 1
4,14911.0,1,201,143711.17,5,5,5,555,Champions,Decile 1

In [51]:
rfm.to_csv("RFM_analysis.csv", index=False)